name: ReformCloud2Placeholders
version: '2.0'
author: derklaro
main: systems.reformcloud.reformcloud2.placeholderapi.PlaceHolderAPIExtensionPlugin

depend:
  - ReformCloud2SpigotExecutor

softdepend:
  - PlaceholderAPI

# Additional
website: 'https://reformcloud.systems'
description: 'The reformcloud placeholder api extension plugin'